name: Deploy to Fly

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "::add-path::$HOME/.fly/bin"

      - name: Show flyctl version
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl version

      - name: Login to Fly (uses token from repo secrets)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl auth whoami || echo "flyctl ready"

      - name: Set Fly secrets (if provided)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROTRADER_APP_KEY: ${{ secrets.PROTRADER_APP_KEY }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          FCM_TOPIC: ${{ secrets.FCM_TOPIC }}
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          # set secrets (Fly will encrypt them)
          flyctl secrets set \
            FIREBASE_SERVICE_ACCOUNT="$FIREBASE_SERVICE_ACCOUNT" \
            PROTRADER_APP_KEY="$PROTRADER_APP_KEY" \
            ALPHA_VANTAGE_KEY="$ALPHA_VANTAGE_KEY" \
            FCM_TOPIC="$FCM_TOPIC" || true

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl deploy --config fly.toml --detach
