name: ProTrader Signal Worker

on:
  schedule:
    # runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # allows manual run

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run worker
        env:
          BACKEND_URL: "https://protraderhack.onrender.com"
          PROTRADER_APP_KEY: "ishaan"
        run: |
          python worker.py
