name: ProTrader Signal Worker

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5   # updated to v5 for latest fixes
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run worker
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          PROTRADER_APP_KEY: ${{ secrets.PROTRADER_APP_KEY }}
        run: python worker.py
